# Preguntas de Análisis

In [1]:
import pandas as pd

categorias = pd.read_parquet("categorias.parquet")
libros = pd.read_parquet("libros.parquet")

print("Categorías:", categorias.shape)
print("Libros:", libros.shape)

Categorías: (50, 5)
Libros: (1000, 17)

In [2]:
print("Columnas de categorias.parquet:")
print(categorias.columns.tolist())

print("\nColumnas de libros.parquet:")
print(libros.columns.tolist())

Columnas de categorias.parquet:
['categoria', 'url_categoria', 'cantidad_libros', 'fecha_extraccion', 'extraido_por']

Columnas de libros.parquet:
['upc', 'titulo', 'categoria', 'descripcion', 'tipo_producto', 'precio_sin_impuesto', 'precio_con_impuesto', 'impuesto', 'moneda', 'disponibilidad', 'cantidad_stock', 'calificacion', 'cantidad_resenas', 'url_libro', 'url_imagen', 'fecha_extraccion', 'extraido_por']

## 1. ¿Cuántas categorías de libros existen?

In [3]:
cantidad_categorias = categorias["categoria"].nunique()

print(f"Existen {cantidad_categorias} categorías de libros.")

Existen 50 categorías de libros.

## 2. ¿Cuántos libros hay en cada categoría?

In [4]:
libros_por_categoria = (
    categorias[
        ["categoria", "cantidad_libros"]
    ]
    .sort_values(
        by="cantidad_libros",
        ascending=False
    )
    .reset_index(drop=True)
)

libros_por_categoria

             categoria  cantidad_libros
0              Default              152
1           Nonfiction              110
2       Sequential Art               75
3        Add a comment               67
4              Fiction               65
5          Young Adult               54
6              Fantasy               48
7              Romance               35
8              Mystery               32
9       Food and Drink               30
10           Childrens               29
11  Historical Fiction               26
12            Classics               19
13              Poetry               19
14             History               18
15      Womens Fiction               17
16              Horror               17
17     Science Fiction               16
18             Science               14
19               Music               13
20            Business               12
21              Travel               11
22          Philosophy               11
23            Thriller               11
24               Humor               10
25       Autobiography                9
26                 Art                8
27            Religion                7
28          Psychology                7
29   Christian Fiction                6
30        Spirituality                6
31           New Adult                6
32    Sports and Games                5
33           Biography                5
34           Self Help                5
35              Health                4
36            Politics                3
37        Contemporary                3
38           Christian                3
39          Historical                2
40          Paranormal                1
41           Parenting                1
42       Adult Fiction                1
43            Academic                1
44       Short Stories                1
45            Suspense                1
46              Novels                1
47            Cultural                1
48             Erotica                1
49               Crime                1

## 3. ¿Cuál es el libro más caro? Si hay varios libros con el mismo precio máximo, se deben mostrar todos.

In [5]:
precio_maximo = libros["precio_con_impuesto"].max()

libros_mas_caros = libros.loc[
    libros["precio_con_impuesto"] == precio_maximo,
    [
        "upc",
        "titulo",
        "categoria",
        "precio_con_impuesto",
        "moneda"
    ]
].reset_index(drop=True)

print(f"Precio máximo: {precio_maximo:.2f} GBP")

libros_mas_caros

Precio máximo: 59.99 GBP

,upc,titulo,categoria,precio_con_impuesto,moneda
0,9cc207168a03470d,The Perfect Play (Play by Play #1),Romance,59.99,GBP

## 4. ¿Hay algún libro que aparezca en más de una categoría? La comparación debe realizarse utilizando el upc.

In [6]:
categorias_por_libro = (
    libros
    .groupby("upc")
    .agg(
        titulo=("titulo", "first"),
        cantidad_categorias=("categoria", "nunique"),
        categorias=(
            "categoria",
            lambda valores: ", ".join(
                sorted(valores.unique())
            )
        )
    )
    .reset_index()
)

libros_en_varias_categorias = categorias_por_libro[
    categorias_por_libro["cantidad_categorias"] > 1
].reset_index(drop=True)

if libros_en_varias_categorias.empty:
    print(
        "No hay libros que aparezcan en más de una categoría "
        "según el UPC."
    )
else:
    print(
        f"Se encontraron {len(libros_en_varias_categorias)} "
        "libros en más de una categoría."
    )

libros_en_varias_categorias

No hay libros que aparezcan en más de una categoría según el UPC.

Empty DataFrame
Columns: [upc, titulo, cantidad_categorias, categorias]
Index: []

## 5. ¿Cuál es el libro más barato de cada categoría? Si hay varios libros con el mismo precio mínimo, se deben mostrar todos.

In [7]:
precio_minimo_por_categoria = (
    libros
    .groupby("categoria")["precio_con_impuesto"]
    .transform("min")
)

libros_mas_baratos = libros.loc[
    libros["precio_con_impuesto"] == precio_minimo_por_categoria,
    [
        "categoria",
        "upc",
        "titulo",
        "precio_con_impuesto",
        "moneda"
    ]
].sort_values(
    by=["categoria", "titulo"]
).reset_index(drop=True)

libros_mas_baratos

,categoria,upc,titulo,precio_con_impuesto,moneda
0,Academic,7093cf549cd2e7de,Logan Kade (Fallen Crest High #5.5),13.12,GBP
1,Add a comment,224fa77d4b248046,The Tipping Point: How Little Things Can Make ...,10.02,GBP
2,Adult Fiction,ed813a848580ba50,Fifty Shades Freed (Fifty Shades #3),15.36,GBP
3,Art,8a150fd8ff5d7686,History of Beauty,10.29,GBP
4,Autobiography,c99761a700ade23f,The Argonauts,10.93,GBP
5,Biography,d69dd8dac66f9f84,Louisa: The Extraordinary Life of Mrs. Adams,16.85,GBP
6,Business,3bebf34ee9330cbd,The Third Wave: An Entrepreneur’s Vision of th...,12.61,GBP
7,Childrens,157f693d9e600ccc,Counting Thyme,10.62,GBP
8,Christian,a322361a37a78d3d,Blue Like Jazz: Nonreligious Thoughts on Chris...,25.77,GBP
9,Christian Fiction,4807043b8218e9ce,Counted With the Stars (Out from Egypt #1),17.97,GBP
10,Classics,6587f46697fc4443,The Hound of the Baskervilles (Sherlock Holmes...,14.82,GBP
11,Contemporary,be3db344a845580b,We Are All Completely Beside Ourselves,24.04,GBP
12,Crime,abeafe151a587d3b,The Long Shadow of Small Ghosts: Murder and Me...,10.97,GBP
13,Cultural,bb8245f52c7cce8f,Amid the Chaos,36.58,GBP
14,Default,f201f263d8c23f97,Greek Mythic History,10.23,GBP
15,Erotica,88c21fcd38e2486e,Dark Notes,19.19,GBP
16,Fantasy,4fa75fc6829431ca,Every Heart a Doorway (Every Heart A Doorway #1),12.16,GBP
17,Fiction,aeff7b87a8e83ebb,I Am Pilgrim (Pilgrim #1),10.60,GBP
18,Food and Drink,f701fae56b645ef7,The Power Greens Cookbook: 140 Delicious Super...,11.05,GBP
19,Health,43c6a960757cf559,The Bulletproof Diet: Lose up to a Pound a Day...,49.05,GBP
20,Historical,eb7459e0c570251d,The Girl You Left Behind (The Girl You Left Be...,15.79,GBP
21,Historical Fiction,24933c712f0bca2f,The Constant Princess (The Tudor Court #1),16.62,GBP
22,History,7f5157bf53065d36,Brilliant Beacons: A History of the American L...,11.45,GBP
23,Horror,af58a74e4b2a23a0,Pet Sematary,10.56,GBP
24,Humor,02b74068fa98d8a4,Old School (Diary of a Wimpy Kid #10),11.83,GBP
25,Music,2ba5ccc84d35006c,Orchestra of Exiles: The Story of Bronislaw Hu...,12.36,GBP
26,Mystery,2d1e337aaf341858,Tastes Like Fear (DI Marnie Rome #3),10.69,GBP
27,New Adult,6e473eff459e809f,The Hook Up (Game On #1),36.29,GBP
28,Nonfiction,985991708c47003e,"The Sleep Revolution: Transforming Your Life, ...",11.68,GBP
29,Novels,0e095ed785af7e43,Suzie Snowflake: One beautiful flake (a self-e...,54.81,GBP
30,Paranormal,e7e87087b1a44711,"Vampire Knight, Vol. 1 (Vampire Knight #1)",15.40,GBP
31,Parenting,ef49db2aaa9bb547,Catastrophic Happiness: Finding Joy in Childho...,37.35,GBP
32,Philosophy,6be3beb0793a53e7,Sophie's World,15.94,GBP
33,Poetry,31001a1210623bd4,Poems That Make Grown Women Cry,14.19,GBP
34,Politics,a18a4f574854aced,Libertarianism for Beginners,51.33,GBP
35,Psychology,4e812d32d64e2431,The Lucifer Effect: Understanding How Good Peo...,10.40,GBP
36,Religion,796c87ddbbaaf8c5,You Are What You Love: The Spiritual Power of ...,21.87,GBP
37,Romance,ecdf73ee66c33b17,Reservations for Two,11.10,GBP
38,Science,0345872b14f9e774,The Origin of Species,10.01,GBP
39,Science Fiction,790ef197c8f236f5,The Project,10.65,GBP
40,Self Help,88ec621893e595d0,You Are a Badass: How to Stop Doubting Your Gr...,12.08,GBP
41,Sequential Art,9429b4d59c537af5,Patience,10.16,GBP
42,Short Stories,1bba4b1ba23ed2d6,The Grownup,35.88,GBP
43,Spirituality,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,GBP
44,Sports and Games,ce42e3de94226b2b,Sugar Rush (Offensive Line #2),24.42,GBP
45,Suspense,e46a164cf310fd7d,Silence in the Dark (Logan Point #4),58.33,GBP
46,Thriller,23356462d1320d61,In Her Wake,12.84,GBP
47,Travel,366a236aa1ea6f07,The Road to Little Dribbling: Adventures of an...,23.21,GBP
48,Womens Fiction,31f5bbf4974d29c9,Some Women,13.73,GBP
49,Young Adult,f36d24c309e87e5b,An Abundance of Katherines,10.00,GBP

## 6. ¿Cuánto más caro o más barato es cada libro respecto al precio promedio de su categoría?

In [8]:
precio_promedio_por_categoria = (
    libros
    .groupby("categoria")["precio_con_impuesto"]
    .transform("mean")
)

diferencia_promedio = libros[
    [
        "upc",
        "titulo",
        "categoria",
        "precio_con_impuesto"
    ]
].copy()

diferencia_promedio["precio_promedio_categoria"] = (
    precio_promedio_por_categoria
)

diferencia_promedio["diferencia"] = (
    diferencia_promedio["precio_con_impuesto"]
    - diferencia_promedio["precio_promedio_categoria"]
)

diferencia_promedio[
    [
        "precio_con_impuesto",
        "precio_promedio_categoria",
        "diferencia"
    ]
] = diferencia_promedio[
    [
        "precio_con_impuesto",
        "precio_promedio_categoria",
        "diferencia"
    ]
].round(2)

diferencia_promedio

,upc,titulo,categoria,precio_con_impuesto,precio_promedio_categoria,diferencia
0,a22124811bfa8350,It's Only the Himalayas,Travel,45.17,39.79,5.38
1,ce60436f52c5ee68,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,49.43,39.79,9.64
2,f9705c362f070608,See America: A Celebration of Our National Par...,Travel,48.87,39.79,9.08
3,1809259a5a5f1d8d,Vagabonding: An Uncommon Guide to the Art of L...,Travel,36.94,39.79,-2.85
4,a94350ee74deaa07,Under the Tuscan Sun,Travel,37.33,39.79,-2.46
...,...,...,...,...,...,...
995,2b5054a4192e9b06,Why the Right Went Wrong: Conservatism--From G...,Politics,52.65,53.61,-0.96
996,3968e3fbf4695d7c,Equal Is Unfair: America's Misguided Fight Aga...,Politics,56.86,53.61,3.25
997,bb8245f52c7cce8f,Amid the Chaos,Cultural,36.58,36.58,0.00
998,88c21fcd38e2486e,Dark Notes,Erotica,19.19,19.19,0.00
999,abeafe151a587d3b,The Long Shadow of Small Ghosts: Murder and Me...,Crime,10.97,10.97,0.00

In [9]:
def clasificar_precio(diferencia):
    if diferencia > 0:
        return "Más caro que el promedio"
    elif diferencia < 0:
        return "Más barato que el promedio"
    else:
        return "Igual al promedio"


diferencia_promedio["comparacion"] = (
    diferencia_promedio["diferencia"]
    .apply(clasificar_precio)
)

diferencia_promedio

,upc,titulo,categoria,precio_con_impuesto,precio_promedio_categoria,diferencia,comparacion
0,a22124811bfa8350,It's Only the Himalayas,Travel,45.17,39.79,5.38,Más caro que el promedio
1,ce60436f52c5ee68,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,49.43,39.79,9.64,Más caro que el promedio
2,f9705c362f070608,See America: A Celebration of Our National Par...,Travel,48.87,39.79,9.08,Más caro que el promedio
3,1809259a5a5f1d8d,Vagabonding: An Uncommon Guide to the Art of L...,Travel,36.94,39.79,-2.85,Más barato que el promedio
4,a94350ee74deaa07,Under the Tuscan Sun,Travel,37.33,39.79,-2.46,Más barato que el promedio
...,...,...,...,...,...,...,...
995,2b5054a4192e9b06,Why the Right Went Wrong: Conservatism--From G...,Politics,52.65,53.61,-0.96,Más barato que el promedio
996,3968e3fbf4695d7c,Equal Is Unfair: America's Misguided Fight Aga...,Politics,56.86,53.61,3.25,Más caro que el promedio
997,bb8245f52c7cce8f,Amid the Chaos,Cultural,36.58,36.58,0.00,Igual al promedio
998,88c21fcd38e2486e,Dark Notes,Erotica,19.19,19.19,0.00,Igual al promedio
999,abeafe151a587d3b,The Long Shadow of Small Ghosts: Murder and Me...,Crime,10.97,10.97,0.00,Igual al promedio

## 7. Suponiendo que se venden todas las unidades disponibles, ¿qué libro produciría el mayor ingreso dentro de cada categoría?

In [10]:
libros_ingresos = libros.copy()

libros_ingresos["ingreso_potencial"] = (
    libros_ingresos["precio_con_impuesto"]
    * libros_ingresos["cantidad_stock"]
)

libros_ingresos[
    [
        "titulo",
        "categoria",
        "precio_con_impuesto",
        "cantidad_stock",
        "ingreso_potencial"
    ]
].head()

,titulo,categoria,precio_con_impuesto,cantidad_stock,ingreso_potencial
0,It's Only the Himalayas,Travel,45.17,19,858.23
1,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,49.43,15,741.45
2,See America: A Celebration of Our National Par...,Travel,48.87,14,684.18
3,Vagabonding: An Uncommon Guide to the Art of L...,Travel,36.94,8,295.52
4,Under the Tuscan Sun,Travel,37.33,7,261.31

In [11]:
ingreso_maximo_por_categoria = (
    libros_ingresos
    .groupby("categoria")["ingreso_potencial"]
    .transform("max")
)

mayor_ingreso_por_categoria = libros_ingresos.loc[
    libros_ingresos["ingreso_potencial"]
    == ingreso_maximo_por_categoria,
    [
        "categoria",
        "upc",
        "titulo",
        "precio_con_impuesto",
        "cantidad_stock",
        "ingreso_potencial",
        "moneda"
    ]
].sort_values(
    by=["categoria", "titulo"]
).reset_index(drop=True)

mayor_ingreso_por_categoria["ingreso_potencial"] = (
    mayor_ingreso_por_categoria[
        "ingreso_potencial"
    ].round(2)
)

mayor_ingreso_por_categoria

,categoria,upc,titulo,precio_con_impuesto,cantidad_stock,ingreso_potencial,moneda
0,Academic,7093cf549cd2e7de,Logan Kade (Fallen Crest High #5.5),13.12,5,65.60,GBP
1,Add a comment,228f74b74f3a08ae,Judo: Seven Steps to Black Belt (an Introducto...,53.90,16,862.40,GBP
2,Adult Fiction,ed813a848580ba50,Fifty Shades Freed (Fifty Shades #3),15.36,3,46.08,GBP
3,Art,ccd9ffa25efabdea,Wall and Piece,44.18,18,795.24,GBP
4,Autobiography,825d6c44da3ca5a6,Lab Girl,40.85,11,449.35,GBP
5,Biography,5b546a46a86a9d8c,Benjamin Franklin: An American Life,48.19,7,337.33,GBP
6,Business,2597b5a345f45e1b,The Dirty Little Secrets of Getting Your Dream...,33.34,19,633.46,GBP
7,Childrens,9528d0948525bf5f,Birdsong: A Story in Pictures,54.64,19,1038.16,GBP
8,Christian,e4ac92d89b946781,(Un)Qualified: How God Uses Broken People to D...,54.00,16,864.00,GBP
9,Christian Fiction,a57b1dcbd6849222,Close to You,49.46,15,741.90,GBP
10,Classics,2798974abc8a58a8,Candide,58.63,4,234.52,GBP
11,Contemporary,a278db6b2b09cf9f,Someone Like You (The Harrisons #2),52.79,14,739.06,GBP
12,Crime,abeafe151a587d3b,The Long Shadow of Small Ghosts: Murder and Me...,10.97,15,164.55,GBP
13,Cultural,bb8245f52c7cce8f,Amid the Chaos,36.58,15,548.70,GBP
14,Default,904208d6aa64b655,Aladdin and His Wonderful Lamp,53.13,19,1009.47,GBP
15,Erotica,88c21fcd38e2486e,Dark Notes,19.19,15,287.85,GBP
16,Fantasy,fa9610a50a1bf149,Masks and Shadows,56.40,16,902.40,GBP
17,Fiction,6957f44c3847a760,Soumission,50.10,20,1002.00,GBP
18,Food and Drink,142d767a56a9254d,The Pioneer Woman Cooks: Dinnertime: Comfort C...,56.41,16,902.56,GBP
19,Health,43c6a960757cf559,The Bulletproof Diet: Lose up to a Pound a Day...,49.05,16,784.80,GBP
20,Historical,39861fc1c0845d15,All the Light We Cannot See,29.87,14,418.18,GBP
21,Historical Fiction,90fa61229261140a,Tipping the Velvet,53.74,20,1074.80,GBP
22,History,4165285e1663650f,Sapiens: A Brief History of Humankind,54.23,20,1084.60,GBP
23,Horror,6f78a0d744c35456,Security,39.25,16,628.00,GBP
24,Humor,f21effc079a2b38a,The Long Haul (Diary of a Wimpy Kid #9),44.07,14,616.98,GBP
25,Music,deda3e61b9514b83,Our Band Could Be Your Life: Scenes from the A...,57.25,19,1087.75,GBP
26,Mystery,e00eb4fd7b871a48,Sharp Objects,47.82,20,956.40,GBP
27,New Adult,08db62f24627e71f,The Matchmaker's Playbook (Wingmen Inc. #1),55.85,15,837.75,GBP
28,Nonfiction,a30b270e25489e5c,The Electric Pencil: Drawings from Inside Stat...,56.06,16,896.96,GBP
29,Novels,0e095ed785af7e43,Suzie Snowflake: One beautiful flake (a self-e...,54.81,9,493.29,GBP
30,Paranormal,e7e87087b1a44711,"Vampire Knight, Vol. 1 (Vampire Knight #1)",15.40,1,15.40,GBP
31,Parenting,ef49db2aaa9bb547,Catastrophic Happiness: Finding Joy in Childho...,37.35,3,112.05,GBP
32,Philosophy,bd261725b99f5983,The Death of Humanity: and the Case for Life,58.11,16,929.76,GBP
33,Poetry,a897fe39b1053632,A Light in the Attic,51.77,22,1138.94,GBP
34,Politics,a18a4f574854aced,Libertarianism for Beginners,51.33,19,975.27,GBP
35,Psychology,ce8666d9b42fc9a0,It Didn't Start with You: How Inherited Family...,56.27,11,618.97,GBP
36,Religion,fce19f9b4a943f22,Don't Be a Jerk: And Other Practical Advice fr...,37.97,16,607.52,GBP
37,Romance,203b7f94b7d6115f,Suddenly in Love (Lake Haven #1),55.99,15,839.85,GBP
38,Science,e4f74c16de34d440,Immunity: How Elie Metchnikoff Changed the Cou...,57.36,16,917.76,GBP
39,Science Fiction,e30f54cea9b38190,Mesaerion: The Best Science Fiction Stories 18...,37.59,19,714.21,GBP
40,Self Help,9ffa38d3b832433a,Online Marketing for Busy Authors: A Step-By-S...,46.35,16,741.60,GBP
41,Sequential Art,3b1c02bac2a429e6,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,19,993.51,GBP
42,Short Stories,1bba4b1ba23ed2d6,The Grownup,35.88,8,287.04,GBP
43,Spirituality,513271dadc1322ae,Chasing Heaven: What Dying Taught Me About Living,37.80,15,567.00,GBP
44,Sports and Games,a9aa3ed5b316470b,"Friday Night Lights: A Town, a Team, and a Dream",51.22,3,153.66,GBP
45,Suspense,e46a164cf310fd7d,Silence in the Dark (Logan Point #4),58.33,8,466.64,GBP
46,Thriller,be5cc846f45496fb,Behind Closed Doors,52.22,18,939.96,GBP
47,Travel,a22124811bfa8350,It's Only the Himalayas,45.17,19,858.23,GBP
48,Womens Fiction,fd8585283fc7d2d7,I Had a Nice Time And Other Lies...: How to fi...,57.36,15,860.40,GBP
49,Young Adult,41164b8ac02a2c42,Aristotle and Dante Discover the Secrets of th...,58.14,14,813.96,GBP

# Notas

## El archivo requirements.txt contiene la lista de librerías instaladas en el entorno virtual y sus versiones. Para eso se utilizó el comando pip freeze > requirements.txt